### ISSUE TITLE
Make node selectors optional for cht-core helm charts

### ISSUE THREAD

**Issue by henokgetachew** [medic/helm-charts#4]
[This](https://github.com/medic/helm-charts/pull/3) PR removes node selectors. 
Node selectors are required when using k3s with mounted disks to the vm. We need to make them optional. 

I think it just suffices to check if that key exists in the helm values and use it if it exists. Otherwise don't use them.

**Comment by Hareet** [comment]
Do we want to switch to `nodeAffinity` ? From [local pvc docs](https://kubernetes.io/docs/concepts/storage/volumes/#local)
imply that's required (/weird)
> You must set a PersistentVolume nodeAffinity when using local volumes. The Kubernetes scheduler uses the PersistentVolume nodeAffinity to schedule these Pods to the correct node.

Other bits of interest that we want to check:
> When using local volumes, it is recommended to create a StorageClass with volumeBindingMode set to WaitForFirstConsumer

> Delaying volume binding ensures that the PersistentVolumeClaim binding decision will also be evaluated with any other node constraints the Pod may have, such as node resource requirements, node selectors, Pod affinity, and Pod anti-affinity.

EKS default storage-classes we use `Immediate`, can't find the storageclass template for k3s. I'll boot up a cluster and check unless you happen to know from docs.

**Comment by henokgetachew** [comment]
re: `nodeAffinity` vs the `nodeSelectors`, I considered it too. The main reasoning in the end came down to simplicity for the people deploying the vms. When deploying k3s clusters, the default node name becomes the actual vm host name that gets provisioned that k3s gets created on. Basically the host name that gets created to be used by whoever sets up the vms. Without folks having to use any kubernetes related functionality, this gets assigned for them automatically based on the name of the vm node they created. i.e. one less thing they'd have to configure/manage. They basically choose the vm host name for that node to make deployments run on it.
