### ISSUE TITLE
Bump update-service-kubernetes in helmchart

### ISSUE THREAD

**Issue by dianabarsan** [medic/helm-charts#8]
upgrade-service 0.32 was released with a fix for clustered couchdb upgrades.

Update the helmcharts and zip to deploy latest version.

Shadow issue for https://github.com/medic/cht-core/issues/8929

**Comment by nydr** [comment]
Resolved by https://github.com/medic/helm-charts/pull/9 (released in chart version [0.2.2](https://github.com/medic/helm-charts/releases/tag/cht-chart-4x-0.2.2)) and will be active in cht-deploy with https://github.com/medic/cht-core/pull/8996

Letting you close @dianabarsan in case you want to keep it open for any reason
